### ISSUE TITLE
Commands not interactive, login not working

### ISSUE THREAD

**Issue by momo-the-monster** [soldair/pinoccio-server#2]
Trying this on a Windows 7 machine. The commands don't seem to go into interactive mode when I run them without flags like:
`pinoccio login`
When I try running with flags or with unflagged variables, login returns without a message:
`pinoccio login -e me@domain.com -p password`
Afterwards, a command that needs a token like pinoccio bridge will fail with the message:
`you must login or register first. try 'pinoccio register'`

**Comment by jgriessen** [comment]
Hi,  have you seen anything from the pinoccio creators about this promise of providing an open version of HQ?  "We will continue to support the Pinoccio API and HQ services that we run until 11:59p PDT, May 31, 2015. We will release the open-source versions of those services well before that date, "

**Comment by soldair** [comment]
hey. i did implement the pinoccio api in a self contained module. https://github.com/Pinoccio/pinoccio-api
ill have to clone it and test it out to see what's "done"

also this is the database layer used by the api module.  https://github.com/Pinoccio/pinoccio-db 
It's a mostly generic database for managing the logic around provisioning meshes with shared keys and incrementing ids. 

I never had time to finish the database replication logic so i kinda never told anyone they should use the server but you really should as long as you keep in mind i would love anyone to get their hands dirty and help out. =)

**Comment by soldair** [comment]
the work to clean up the hq UI and open it up may have died on the vine.

**Comment by jgriessen** [comment]
On 09/01/2015 10:03 AM, Ryan Day wrote:

> the work to clean up the hq UI and open it up may have died on the vine.

Hmm.. Doesn't that bug you?  They promised to make it available, if not continue improving it.

I just stumbled onto this platform and the web apps and server code,
and am interested in whatever might be FOSS licensed.

John Griessen

**Comment by soldair** [comment]
only so much time in the day. :)

To be honest I never used hq much. i found the command line tools to be
exactly the ones I needed.

**Comment by jgriessen** [comment]
I just got word from filament that they plan to release an open version of HQ by year end.  So they are keeping their promises.
